#!/usr/bin/env bash
# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Exit immediately if a command fails
set -e

echo "Configuring Bazel for QNX cross-compilation..."

# 1. Ensure the developer actually activated their QNX license
if [ -z "$QNX_TARGET" ] || [ -z "$QNX_HOST" ]; then
    echo "ERROR: QNX environment not detected."
    echo "Please source your QNX SDP environment script first."
    echo "Example: source ~/qnx800/qnxsdp-env.sh"
    exit 1
fi

# 2. Generate a local .bazelrc file containing their exact absolute paths
cat <<EOF > qnx_local.bazelrc
# ==============================================================================
# AUTO-GENERATED BY configure.sh - DO NOT COMMIT
# ==============================================================================
# Injected OpenSSL paths
build:per-arm64-qnx --action_env=OPENSSL_INCLUDE_DIR=$QNX_TARGET/usr/include
build:per-arm64-qnx --action_env=OPENSSL_LIB_DIR=$QNX_TARGET/aarch64le/usr/lib

# Injected CC wrapper to bypass the Bazel sandbox environment poisoning
build:per-arm64-qnx --action_env=CC_aarch64_unknown_nto_qnx800="env QNX_HOST=$QNX_HOST $QNX_HOST/usr/bin/qcc"
EOF

echo "Success! 'qnx_local.bazelrc' generated."
echo "You can now run raw bazel commands."
