# Parsec service configuration for pkcs11-engine
# Provider: libcryptoki.so (PKCS#11 software token)
# Auth:     UnixPeerCredentials (uid-based, no password required)

[core_settings]
log_level     = "info"
log_timestamp = true

[listener]
listener_type = "DomainSocket"
socket_path   = "/home/omar/.pkcs11-engine/parsec/run/parsec.sock"
timeout       = 5000

[authenticator]
auth_type = "UnixPeerCredentials"

[[key_manager]]
name         = "on-disk-manager"
manager_type = "OnDisk"
store_path   = "/home/omar/.pkcs11-engine/parsec/mappings"

[[provider]]
name                       = "pkcs11-provider"
provider_type              = "Pkcs11"
key_info_manager           = "on-disk-manager"
library_path               = "/home/omar/Downloads/pkcs11-engine/target/release/libcryptoki.so"
slot_number                = 0
user_pin                   = "1234"
software_public_operations = false
